//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public Nullable<int> stu_id { get; set; }
        public string stu_name { get; set; }
        public Nullable<decimal> stu_phoneno { get; set; }
        public string stu_email_id { get; set; }
        public Nullable<int> stu_ranking { get; set; }
        public string stu_branch { get; set; }
        public Nullable<int> empid { get; set; }
    }
}
